/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.*;
import DAO.DashDAO;
import java.awt.BorderLayout;
import java.awt.Color;


/**
 *
 * @author jateixeira
 */
public class DashBoards extends javax.swing.JFrame {
    
    
    private JComboBox<String> comboMes;
    private JComboBox<String> comboAno;
    private JButton btnGerar;
    private JPanel panelGrafico;
    private JButton btnVoltar;
    
    public DashBoards() {
       this.setLocationRelativeTo(null);
        
        panelGrafico = new JPanel();
        panelGrafico.setLayout(new BorderLayout());
        add(panelGrafico, BorderLayout.CENTER);
        
        setTitle("Dashboard Consumo");
        setSize(1400, 750);
        setForeground(Color.yellow);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        comboMes = new JComboBox<>(new String[]{
            "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
            "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
        });

        comboAno = new JComboBox<>(new String[]{"2023", "2024", "2025"});
        btnGerar = new JButton("Gerar Gráfico");
        btnVoltar = new JButton("Voltar");

        JPanel topPanel = new JPanel();
        topPanel.add(new JLabel("Mês:"));
        topPanel.add(comboMes);
        topPanel.add(new JLabel("Ano:"));
        topPanel.add(comboAno);
        topPanel.add(btnGerar);
        topPanel.add(btnVoltar);
        

        add(topPanel, "North");
        
        btnVoltar.addActionListener(e -> {
    // Fecha o DashBoards
    this.dispose();
    
    // Abre a tela principal (substitua TelaPrincipal pela sua classe real)
    TelaMenu tela = new TelaMenu();
    tela.setVisible(true);
});

        btnGerar.addActionListener(e -> gerarGrafico());
       
        
        setLocationRelativeTo(null);
    
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
private void gerarGrafico() {
    String mes = comboMes.getSelectedItem().toString();
    String ano = comboAno.getSelectedItem().toString();

    DashDAO dao = new DashDAO();
    DefaultCategoryDataset dataset = dao.getConsumoPorMesAno(mes, ano);

    JFreeChart chart = ChartFactory.createBarChart(
        "Consumo por Tipo (" + mes + "/" + ano + ")",
        "Tipo",
        "Valor (R$)",
        dataset
    );

    // Pega o renderer e habilita labels
    org.jfree.chart.renderer.category.BarRenderer renderer =
            (org.jfree.chart.renderer.category.BarRenderer) chart.getCategoryPlot().getRenderer();

    // Formatar em R$ (pt-BR)
    java.text.NumberFormat nf = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt", "BR"));

    // Versão compatível (funciona em muitas instalações)
    renderer.setBaseItemLabelGenerator(new org.jfree.chart.labels.StandardCategoryItemLabelGenerator("{2}", nf));
    renderer.setBaseItemLabelsVisible(true);

    // Monta o painel e atualiza a UI
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(750, 400));
    

    panelGrafico.removeAll();
    panelGrafico.add(chartPanel, BorderLayout.CENTER);
    panelGrafico.revalidate();
    panelGrafico.repaint();
}


    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new DashBoards().setVisible(true));
    }
}

