
package VIEW;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import DAO.CadastroNovaFaturaGipDAO;
import DTO.CadastroNovaFaturaGipDTO; 
import java.sql.ResultSet;
import javax.swing.JOptionPane;



/**
 *
 * @author jateixeira
 */
public class TelaCadastroNovaFatura extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroNovaFatura
     */
    public TelaCadastroNovaFatura() {
       
        initComponents();
        AutoCompleteDecorator.decorate(TiposComboBox);
        setExtendedState((int) CENTER_ALIGNMENT);
        this.setLocationRelativeTo(null);
         
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedidorTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BarrasTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InstalacaoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CargaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Medidor1TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RuaTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        NumeroTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BairroTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TiposComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        UnidadeTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        AvencaTxt = new javax.swing.JCheckBox();
        CadastrarBtn = new javax.swing.JButton();
        ReduzidoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        VoltarBtn = new javax.swing.JButton();

        MedidorTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Nova Fatura:");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Código de Barras:");

        BarrasTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BarrasTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BarrasTextField.setName(""); // NOI18N

        jLabel2.setText("Instalação:");

        InstalacaoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Carga Levantada:");

        CargaTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Medidor de Instalação:");

        Medidor1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Rua:");

        RuaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuaTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Número:");

        NumeroTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Bairro:");

        BairroTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BairroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipos:");

        TiposComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saúde", "Escola", "PP", "Praça", "SC", "Ruas", "VD", "IP", "PP Separado", "Média Tensão", "Eco Ponto" }));
        TiposComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TiposComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiposComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Unidade:");

        jLabel11.setText("Avença:");

        AvencaTxt.setText("Não");
        AvencaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvencaTxtActionPerformed(evt);
            }
        });

        CadastrarBtn.setText("CADASTRAR");
        CadastrarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CadastrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarBtnActionPerformed(evt);
            }
        });
        CadastrarBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CadastrarBtnKeyPressed(evt);
            }
        });

        ReduzidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReduzidoTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("CADASTRO DE NOVA INSTALAÇÃO");

        VoltarBtn.setText("VOLTAR");
        VoltarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        VoltarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Medidor1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(TiposComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(210, 210, 210))
                        .addComponent(UnidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CargaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(InstalacaoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(AvencaTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RuaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(ReduzidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BarrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstalacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Medidor1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(RuaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(ReduzidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TiposComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UnidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvencaTxt)
                    .addComponent(jLabel11))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        ReduzidoTxt.setVisible(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarBtnActionPerformed
        
        String text = BarrasTextField.getText();
                int length = text.length();
                String lastSixChars = "";

                if (length >= 8) {
                    lastSixChars = text.substring(length - 8);
                } else {
                    lastSixChars = text;
                }
                
                 ReduzidoTxt.setText(lastSixChars); 
                
        String Rua, Bairro, Tipos, CodigoBarras, Instalacao, CargaLevantada, MedidorInstalacao, Numero, CodRed, Unidade, Avenca; 
        
        
        
        Rua = RuaTextField.getText();
        Bairro = BairroTextField.getText();
        Tipos = (String) TiposComboBox.getSelectedItem(); //uso esse código na combobox para cair no bd o item selecionado da combobox
        //troquei o tipo do combobox de "string" para "object" e fiz esse código, fazendo assim aparecer a opção selecionada no combobox
        CodigoBarras = BarrasTextField.getText();
        Instalacao = InstalacaoTextField.getText();
        CargaLevantada = CargaTextField.getText();
        MedidorInstalacao = Medidor1TextField.getText();
        Numero = NumeroTextField.getText();
        CodRed = ReduzidoTxt.getText();
        Unidade = UnidadeTxt.getText();
        Avenca = AvencaTxt.getText();
        
        CadastroNovaFaturaGipDTO objfaturasgipdto = new CadastroNovaFaturaGipDTO();
        
        objfaturasgipdto.setCodigoBarras_faturanova(CodigoBarras);
        objfaturasgipdto.setBairro_faturanova(Bairro);
        objfaturasgipdto.setRua_faturanova(Rua);
        objfaturasgipdto.setTipos_faturanova(Tipos);
        objfaturasgipdto.setInstalacao_faturanova(Instalacao);
        objfaturasgipdto.setCargaLevantada_faturanova(CargaLevantada);
        objfaturasgipdto.setMedidorInstalacao_faturanova(MedidorInstalacao);
        objfaturasgipdto.setNumero_faturanova(Numero);
        objfaturasgipdto.setCodBarrasRed_faturanova(CodRed);
        objfaturasgipdto.setUnidade_faturanova(Unidade);
        objfaturasgipdto.setAvenca_faturanova(Avenca);
        
        CadastroNovaFaturaGipDAO objfaturasgipdao = new CadastroNovaFaturaGipDAO();
        
        
        objfaturasgipdao.cadastrarFatura(objfaturasgipdto);
        
        if(AvencaTxt.isSelected()){
            AvencaTxt.setText("Sim");
        }else{
            AvencaTxt.setText("Não");
        }
        
        
        /*MedidorInstalacao = Medidor1TextField.getText();

        boolean medidorExiste = objfaturasgipdao.verificarMedidorExistente(MedidorInstalacao);

        if (medidorExiste) {
            JOptionPane.showMessageDialog(this, "Medidor de Instalação já existe no banco de dados. Cadastro não permitido.");
            return; // Retorna imediatamente, impedindo o cadastro
        }
        
        objfaturasgipdao.cadastrarFatura(objfaturasgipdto);*/
       
         BarrasTextField.setText("");
         InstalacaoTextField.setText("");
         CargaTextField.setText("");
         Medidor1TextField.setText("");
         RuaTextField.setText("");
         NumeroTextField.setText("");
         BairroTextField.setText("");
         TiposComboBox.setSelectedIndex(0); //serve para limpar o campo selecionado da combobox
         UnidadeTxt.setText("");
         
         
        
    }//GEN-LAST:event_CadastrarBtnActionPerformed

    private void BairroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroTextFieldActionPerformed

    private void TiposComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiposComboBoxActionPerformed
       
    }//GEN-LAST:event_TiposComboBoxActionPerformed

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        
        //esse código serve para mudar de uma tela para outra 
        TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
        //esse fecha a tela     
            this.dispose();
        
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void CadastrarBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CadastrarBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrarBtnKeyPressed

    private void AvencaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvencaTxtActionPerformed

        //se o checkbox estiver selecionado muda para sim, se ele estiver vazio, muda para não

        if(AvencaTxt.isSelected()){
            AvencaTxt.setText("Sim");
        }else{
            AvencaTxt.setText("Não");
        }
    }//GEN-LAST:event_AvencaTxtActionPerformed

    private void RuaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuaTextFieldActionPerformed

    private void ReduzidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReduzidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReduzidoTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroNovaFatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AvencaTxt;
    private javax.swing.JTextField BairroTextField;
    private javax.swing.JTextField BarrasTextField;
    private javax.swing.JButton CadastrarBtn;
    private javax.swing.JTextField CargaTextField;
    private javax.swing.JTextField InstalacaoTextField;
    private javax.swing.JTextField Medidor1TextField;
    private javax.swing.JTextField MedidorTextField;
    private javax.swing.JTextField NumeroTextField;
    private javax.swing.JTextField ReduzidoTxt;
    private javax.swing.JTextField RuaTextField;
    private javax.swing.JComboBox<Object> TiposComboBox;
    private javax.swing.JTextField UnidadeTxt;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
     
        /*String Rua, Bairro, Tipos, CodigoBarras, Instalacao, CargaLevantada, MedidorInstalacao, Numero; 
        
        Rua = RuaTextField.getText();
        Bairro = BairroTextField.getText();
        Tipos = (String) TiposComboBox.getSelectedItem(); //uso esse código na combobox para cair no bd o item selecionado da combobox
        //troquei o tipo do combobox de "string" para "object" e fiz esse código, fazendo assim aparecer a opção selecionada no combobox
        CodigoBarras = BarrasTextField.getText();
        Instalacao = InstalacaoTextField.getText();
        CargaLevantada = CargaTextField.getText();
        MedidorInstalacao = Medidor1TextField.getText();
        Numero = NumeroTextField.getText();
        
        CadastroNovaFaturaGipDTO objfaturasgipdto = new CadastroNovaFaturaGipDTO();
        objfaturasgipdto.setCodigoBarras_faturanova(CodigoBarras);
        objfaturasgipdto.setBairro_faturanova(Bairro);
        objfaturasgipdto.setRua_faturanova(Rua);
        objfaturasgipdto.setTipos_faturanova(Tipos);
        objfaturasgipdto.setInstalacao_faturanova(Instalacao);
        objfaturasgipdto.setCargaLevantada_faturanova(CargaLevantada);
        objfaturasgipdto.setMedidorInstalacao_faturanova(MedidorInstalacao);
        objfaturasgipdto.setNumero_faturanova(Numero);
       
        
        CadastroNovaFaturaGipDAO objfaturasgipdao = new CadastroNovaFaturaGipDAO();
        objfaturasgipdao.cadastrarFatura(objfaturasgipdto);
        
         BarrasTextField.setText("");
         InstalacaoTextField.setText("");
         CargaTextField.setText("");
         Medidor1TextField.setText("");
         RuaTextField.setText("");
         NumeroTextField.setText("");
         BairroTextField.setText("");
         TiposComboBox.setSelectedIndex(0); //serve para limpar o campo selecionado da combobox
         */
}
/*
CÓDIGO PENSADO POR: JEFF 
E DESENVOLVIDO POR: MATHEUS FELIPE lEITE JANUÁRIO
*/